<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Room Type';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url('room', array('action' => 'index')); ?>">Room Type List</a><span class="divider">/</span>
        </li>
        <li>
            <a href="#">Edit Room Type</a>
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-edit"></i>Edit Room Type</h2>
            <div class="box-icon">
<!--							<a href="#" class="btn btn-setting btn-round"><i class="icon-cog"></i></a>
                <a href="#" class="btn btn-minimize btn-round"><i class="icon-chevron-up"></i></a>
                <a href="#" class="btn btn-close btn-round"><i class="icon-remove"></i></a>-->
            </div>
        </div>
        <div class="box-content">
            <?php
            $form = $this->form;
            $form->setAttribute('action', $this->url('room', array('action' => 'edit', 'id' => $this->id)));
            $form->setAttribute('method', "POST");
            $form->prepare();
            ?>
            <?php echo $this->form()->openTag($form); ?>
            <?php foreach ($form as $element) : ?>

                <div class="control-group <?php
            if ($this->formElementErrors($element))
                echo "error"
                ?>">
                    <label class="control-label"><?php echo $element->getLabel() ?></label>
                    <div class="controls">
                        <?php echo $this->formElement($element);
                        if ($this->formElementErrors($element)):
                            ?>
                            <span class="help-inline"><?php echo $this->formElementErrors($element) ?></span>
    <?php endif; ?>
                    </div>
                </div>

            <?php endforeach; ?>

<?php echo $this->form()->closeTag(); ?>
        </div>
    </div><!--/span-->

</div><!--/row-->
