
<div>
    <ul class="breadcrumb">
        <li>
            <a href="#">Home</a> <span class="divider">/</span>
        </li>
        <li>
            <a href="<?php echo $this->url('room', array('action' => 'index')); ?>">Room Type List</a>
        </li>
    </ul>
</div>

<div class="row-fluid sortable">
    <div class="box span12">
        <div class="box-header well" data-original-title>
            <h2><i class="icon-user"></i>Room Type List</h2>
            <div style="float:right">
                <a href="<?php echo $this->url('room', array('action' => 'add')); ?>" class="btn btn-primary btn-round">Add</a>
            </div>
        </div>
        <?php if (count($list)): ?>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Type</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php  foreach ($this->list as $row): ?>
                            <tr>
                                <td><?php echo $row->id; ?></td>
                                <td class="center"><?php echo $row->type; ?></td>
                                <td class="center"><?php echo $row->desc; ?></td>
                                <td class="center">
                                    <a class="btn btn-success" href="<?php echo $this->url('room', array('action' => 'edit', 'id' => $row->id)); ?>">
                                        <i class="icon-zoom-in icon-white"></i>
                                        View
                                    </a>
                                    <a class="btn btn-info" href="<?php echo $this->url('room', array('action' => 'edit', 'id' => $row->id)); ?>">
                                        <i class="icon-edit icon-white"></i>
                                        Edit
                                    </a>
                                    <a class="btn btn-danger" href="<?php echo $this->url('room', array('action' => 'delete', 'id' => $row->id)); ?>">
                                        <i class="icon-trash icon-white"></i>
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        <?php endforeach;  ?>
                    </tbody>
                </table>
            </div>
        <?php endif; ?>
    </div><!--/span-->

</div><!--/row-->

<?php echo $this->paginationControl($list, "All", "pager.phtml",array('route' => $this->route)); ?>